### ISSUE TITLE
ラベルの参照が未解決になる

### ISSUE THREAD

**Issue by yumunet** [vain0x/hsp3-ginger#12]
イシュー失礼します。「[VSCodeでHSP3開発を超快適にしよう！ [2023年]](https://qiita.com/umuy/items/8e8e6f1e4ccc0387be2c)」を書いた者です。
記事をご覧くださった上に、HSP3 アナライザー・ミニ (LSP) の更新までしていただきありがとうございます。変更点を見るに細かいところまでご覧いただけたようで恐れ多いですがとても嬉しいです！

その上で大変恐縮ですが、v0.5.0からラベルの参照位置が「(未解決)」となっており、「定義へ移動」などができなくなっているようです。
例えば、以下のコードで1行目の`*label`にカーソルを合わせても「label (未解決)」と表示され、定義へ移動もできません。
```
goto *label
*label
```

ご確認いただけると幸いです。

**Comment by vain0x** [comment]
ありがとうございます。いったん以前の挙動に戻して対応しました (v0.5.1)

**Comment by yumunet** [comment]
ご対応ありがとうございます
